{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-cost-optimizer.fullname" . }}-postgresql
  labels:
    {{- include "k8s-cost-optimizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.postgresql.url | quote }}
{{- end }}
